### ISSUE TITLE
Gourgeist Sprite

### ISSUE THREAD

**Issue by Or1onCL** [msikma/pokesprite#69] opened 2020-03-22 00:26 UTC
Hi, Gourgeist has the same image for all sizes
![gourgeist](https://user-images.githubusercontent.com/62489107/77239516-75a41c80-6bba-11ea-84bc-33bf5e2f9895.PNG)

**Comment by msikma** [comment] 2020-03-22 22:14
Yes, it's unfortunate but this is deliberate. (Hover over the "average" etc. text and you'll see a tooltip stating these are aliases of the default form.)

In Gen 7 we had custom made sprites for each size, because the Gen 7 sprites are very small and much easier to modify. They were not great, but they looked OK and they worked. The game itself does not provide separate sprites.

In Gen 8, we don't use these anymore because there's a whole new sprite. If we want to have different sprites for each size, we'll have to make them ourselves.

I'm open to using custom sprites again, but I'd be hesitant to accept submitted sprites unless they were really well made by a good artist, since the new sprites are a lot larger and have a lot less margin for error. So it's not nearly as easy as before to hack up some changes.

**Comment by msikma** [comment] 2020-03-27 16:53
Closing this for now. Maybe someday we'll be able to bring back unique sprites for these, with the caveats I've mentioned in mind. For now this is by design though, as unfortunate as it is. It is possible to still use the old sprites, of course:

![](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen7x/regular/pumpkaboo-small.png) ![](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen7x/regular/pumpkaboo.png) ![](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen7x/regular/pumpkaboo-large.png) ![](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen7x/regular/pumpkaboo-super.png)

![](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen7x/regular/gourgeist-small.png) ![](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen7x/regular/gourgeist.png) ![](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen7x/regular/gourgeist-large.png) ![](https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen7x/regular/gourgeist-super.png)

**Closed by msikma** 2020-03-27 16:53 UTC
